# Generated by Django 5.0.3 on 2024-05-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_chat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
    ]
