# Generated by Django 5.0.3 on 2024-04-06 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 5, 48, 10, 109996, tzinfo=datetime.timezone.utc)),
        ),
    ]
